M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Sun 26 May 2024 19:57:31 EEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-26T19:57:31+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0512
%
G90
G05
T1
X2.512Y-4.22
X2.8262Y-4.22
X3.2062Y-4.22
X3.5204Y-4.22
T2
X4.5262Y-3.2383
T3
X4.4956Y-3.86
X4.5008Y-2.315
X4.7712Y-3.86
X4.7764Y-2.315
T4
X4.5262Y-2.945
M30
